### ISSUE TITLE
Typo in Module import

### ISSUE THREAD

**Issue by akellne** [dschep/django-xor-formfields#7]
In the pip provided version django_xor_formfields-0.1.0 there seems to be a typo in the module import, i.e. an 's' is missing at the end.

`
/env/local/lib/python2.7/site-packages/xorformfields/forms/fields.py", line 14, in <module>
    from django.forms.util import ErrorList
ImportError: No module named util
`

**Comment by Robjuan** [comment]
confirmed, this module was change from 'util' to 'utils' in django
